### ISSUE TITLE
Take me to Twitter now!

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#51]
Should be the text instead of Take me away! 

<img width="439" alt="screenshot 2017-05-03 12 29 56" src="https://cloud.githubusercontent.com/assets/464519/25657077/54533cac-2ffc-11e7-80d6-3e53ece4737d.png">

**Comment by rowanvb** [comment]
We gave this idea some thought, but since extracting a nice title (not like the blacklist style) is rather difficult. There are too many cases where this would turn out to be too difficult to implement in a nice way. Although I have thought of comparing the pagetitle to the domain of the website and detecting matches (i.e. facebook.com & "Facebook - Sign up or Log in"). But again this would definitely not work in every case.

So although the idea is actually pretty nice, we are going to prioritize other stuff first.
