### ISSUE TITLE
endpoint send statistics back to

### ISSUE THREAD

**Issue by mircealungu** [RUGSoftEng/2017-The-Distraction-Shield#69]
https://github.com/mircealungu/Zeeguu-API/blob/master/zeeguu_api/api/upload_user_activity_data.py#L12

**Comment by rowanvb** [comment]
This can only accept a single log entry am I correct?
I've setup a logger module which is able to log all data, which we store in our storage first. Then after a specific time interval, a post request is sent, containing the entire log file. 

this format is a simple JSON string:
{"id":"5f146d00-423a-11e7-ba2d-2115c6465887","event":"changed GreenToRedSlider to: 21","time":"2017-05-26T18:59:43.254Z"}{"id":"5f146d00-423a-11e7-ba2d-2115c6465887","event":"changed GreenToRedSlider to: 10","time":"2017-05-26T18:59:46.734Z"}

I think I'll extract the values of the change from the event.
It would make more sense to send the entire file instead of sending a request on every change right?
Also, we need to send the data to https://zeeguu.unibe.ch/api/upload_user_activity_data in this case right?

**Comment by Daffurn** [comment]
I believe this is done now
